version: 2
updates:
    -   package-ecosystem: "github-actions"
        directory: "/"
        schedule:
            interval: weekly
        open-pull-requests-limit: 5
        groups:
            github_actions_dependencies:
                patterns:
                    - "*"
    -   package-ecosystem: composer
        directory: "/"
        schedule:
            interval: weekly
        open-pull-requests-limit: 10
        groups:
            symfony_dependencies:
                patterns:
                    - "symfony/*"
            dependencies:
                patterns:
                    - "*"
                exclude-patterns:
                    - "symfony/*"
    -   package-ecosystem: docker
        directory: "/"
        schedule:
            interval: weekly
        open-pull-requests-limit: 5
        groups:
            docker_dependencies:
                patterns:
                    - "*"
    -   package-ecosystem: composer
        directory: "/tools/02_phpstan"
        schedule:
            interval: weekly
        open-pull-requests-limit: 3
        groups:
            tools_phpstan_dependencies:
                patterns:
                    - "*"
    -   package-ecosystem: composer
        directory: "/tools/03_psalm"
        schedule:
            interval: weekly
        open-pull-requests-limit: 3
        groups:
            tools_psalm_dependencies:
                patterns:
                    - "*"
    -   package-ecosystem: composer
        directory: "/tools/04_symplify"
        schedule:
            interval: weekly
        open-pull-requests-limit: 3
        groups:
            tools_symplify_dependencies:
                patterns:
                    - "*"
    -   package-ecosystem: composer
        directory: "/tools/05_infection"
        schedule:
            interval: weekly
        open-pull-requests-limit: 3
        groups:
            tools_infection_dependencies:
                patterns:
                    - "*"
    -   package-ecosystem: composer
        directory: "/tools/06_php-coveralls"
        schedule:
            interval: weekly
        open-pull-requests-limit: 3
        groups:
            tools_php-coveralls_dependencies:
                patterns:
                    - "*"
    -   package-ecosystem: composer
        directory: "/tools/07_phpinsights"
        schedule:
            interval: weekly
        open-pull-requests-limit: 3
        groups:
            tools_phpinsights_dependencies:
                patterns:
                    - "*"
    -   package-ecosystem: composer
        directory: "/tools/08_phpmetrics"
        schedule:
            interval: weekly
        open-pull-requests-limit: 3
        groups:
            tools_phpmetrics_dependencies:
                patterns:
                    - "*"
    -   package-ecosystem: composer
        directory: "/tools/09_rector"
        schedule:
            interval: weekly
        open-pull-requests-limit: 3
        groups:
            tools_rector_dependencies:
                patterns:
                    - "*"
    -   package-ecosystem: composer
        directory: "/tools/10_composer"
        schedule:
            interval: weekly
        open-pull-requests-limit: 3
        groups:
            tools_composer_dependencies:
                patterns:
                    - "*"
    -   package-ecosystem: composer
        directory: "/tools/11_phplint"
        schedule:
            interval: weekly
        open-pull-requests-limit: 3
        groups:
            tools_phplint-dependencies:
                patterns:
                    - "*"
    -   package-ecosystem: composer
        directory: "/tools/12_php-parallel-lint"
        schedule:
            interval: weekly
        open-pull-requests-limit: 3
        groups:
            tools_php-parallel-lint_dependencies:
                patterns:
                    - "*"
