# See https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/doc/symfony4.md
services:
    Gedmo\Timestampable\TimestampableListener:
        tags:
            - { name: doctrine.event_listener, connection: default, event: 'prePersist' }
            - { name: doctrine.event_listener, connection: default, event: 'onFlush' }
            - { name: doctrine.event_listener, connection: default, event: 'loadClassMetadata' }

    Gedmo\Blameable\BlameableListener:
        tags:
            - { name: doctrine.event_listener, connection: default, event: 'prePersist' }
            - { name: doctrine.event_listener, connection: default, event: 'onFlush' }
            - { name: doctrine.event_listener, connection: default, event: 'loadClassMetadata' }
