services:
    EasyCorp\EasyLog\EasyLogHandler:
        public: false
        arguments: ['php://stdout']
        # Use below if you're not running application in container
        #arguments: ['%kernel.logs_dir%/%kernel.environment%-readable.log']
