monolog:
    handlers:
        main:
            type: stream
            path: php://stderr
            level: debug
            channels: ['!event']
        firephp:
            type: firephp
            level: info
        chromephp:
            type: chromephp
            level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
