monolog:
    handlers:
        main:
            type: buffer
            handler: easylog
            channels: ['!event']
            level: debug
        easylog:
            type: service
            id: EasyCorp\EasyLog\EasyLogHandler
        firephp:
            type: firephp
            level: info
        chromephp:
            type: chromephp
            level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]

