monolog:
    handlers:
        main:
            type: stream
            path: "php://stdout"
            # Use below if you're not running application in container
            #path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        firephp:
            type: firephp
            level: info
        chromephp:
            type: chromephp
            level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        buffered:
            type: buffer
            handler: easylog
            channels: ['!event']
            level: debug
        easylog:
            type: service
            id: EasyCorp\EasyLog\EasyLogHandler
