services:
    ProxyManager\Factory\AccessInterceptorValueHolderFactory:
        class: ProxyManager\Factory\AccessInterceptorValueHolderFactory

    doctrine.dbal.default_connection.stopwatch:
        class: Doctrine\DBAL\Connection
        decorates: doctrine.dbal.default_connection
        factory: [ '@App\Decorator\StopwatchDecorator', decorate ]
        arguments: [ '@doctrine.dbal.default_connection.stopwatch.inner' ]

    symfony.component.serializer.stopwatch:
        class: Symfony\Component\Serializer\Serializer
        decorates: serializer
        factory: [ '@App\Decorator\StopwatchDecorator', decorate ]
        arguments: [ '@symfony.component.serializer.stopwatch.inner' ]
