name: Harden runner
description: Harden the runner by auditing all outbound calls (step-security/harden-runner)
runs:
  using: composite
  steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
      with:
        egress-policy: audit
