# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Vulnerability Scan
on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  scan:
    name: Scan docker image with trivy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set tag var
        id: vars
        run: echo ::set-output name=docker_tag::$(echo ${GITHUB_REF} | cut -d'/' -f3)-${GITHUB_SHA}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag symfony-flex-backend:${{ steps.vars.outputs.docker_tag }}

      - name: Scan image with trivy
        uses: homoluctus/gitrivy@master
        with:
          image: symfony-flex-backend:${{ steps.vars.outputs.docker_tag }}
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          ignore_unfixed: true
          token: '${{ secrets.GITHUB_TOKEN }}'
